packages:
  - apps/*
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - es5-ext

onlyBuiltDependencies:
  - '@nestjs/core'
  - better-sqlite3
  - core-js
  - esbuild
