packages:
  - apps/*
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

allowBuilds:
  "@nestjs/core": false
  "@parcel/watcher": true
  "@scarf/scarf": false
  better-sqlite3: false
  esbuild: true

minimumReleaseAgeExclude:
  - lucide-react@1.32.0
